### ISSUE TITLE
How to accept self-signed certificate in browser for IBP console

### ISSUE THREAD

**Issue by stefanvogel65** [ibm-cloud-docs/blockchain-rhos#2]
The following URL describes how to accept the self-signed certificate in browser for the Kubernetes service.
https://cloud.ibm.com/docs/services/blockchain-rhos?topic=blockchain-rhos-ibp-v2-troubleshooting#ibp-v2-troubleshooting-accept-tls
However, these instructions do not apply to IBP on the free Kubernetes cluster as the URL is of a different format. How does this work for the free service?

**Comment by pamandrejko** [comment]
You need to restart the associated pod.
For the free service you can use the IBM Dashboard or kubectl to delete the pod and it will restart.
