### ISSUE TITLE
Step 4 "Join peer to channel" fails with error

### ISSUE THREAD

**Issue by stefanvogel65** [ibm-cloud-docs/blockchain-rhos#3]
Hi, I am trying to follow the Join a network tutorial and fail at step 4: https://cloud.ibm.com/docs/blockchain-rhos?topic=blockchain-rhos-ibp-console-join-network#ibp-console-join-network-join-peer-org2. The error occurs when clicking "Join channel": 

```
Peer Org2 did not respond to the join channel request.
unable to get block: grpc web proxy's message: 
"Response closed without headers". 
This can happen when encountering CORS or untrusted TLS issues with the grpc web proxy.
```

I use a 1st IBP network on RHOS cluster on IBM Cloud and a 2nd IBP instance as IBP SaaS on a free Kubernetes cluster on IBM Cloud. The 1st network is built following the "Build a network tutorial" on https://cloud.ibm.com/docs/blockchain-rhos?topic=blockchain-rhos-ibp-console-build-network#ibp-console-build-network. The error happens on the 2nd IBP instance.

**Comment by pamandrejko** [comment]
@stefanvogel65 Thank you for this comment. We are looking into it and will get back to you.

**Comment by pamandrejko** [comment]
Have you tried restarting Peer Org2?

**Comment by pamandrejko** [comment]
No response so closing. 

Updated content is available here:
Software v2.1.2: https://cloud.ibm.com/docs/blockchain-sw?topic=blockchain-sw-ibp-console-join-network
